spring.application.name=auth-service
server.port=0

# Eureka Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.instance.prefer-ip-address=true

# JWT Properties
app.jwtSecret=ecommerceSecretKey123456789012345678901234567890
app.jwtExpirationMs=86400000
app.jwtCookieName=auth-token


# Frontend URL for CORS
frontend.url=http://localhost:5173

# User Service URL for Feign client - using service discovery properly
# Note: We don't need the /public part here as it's set in the @FeignClient path
user-service.url=http://user-service

# Increase logging for debugging
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.ecommerce.auth=DEBUG

# Email (Gmail App) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhdang.gemini@gmail.com
spring.mail.password=ufytlkqzgttuoell
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email verification
app.email.verification.expiration=86400000
app.email.verification.url=${frontend.url}/verify?token=
app.email.reset-password.url=${frontend.url}/reset-password?token=