# Config Server Configuration
spring.application.name=config-server
server.port=8888

# Git Repository Configuration
spring.cloud.config.server.git.uri=file:///c:/Users/Minh/Desktop/Spring Projects/sb-ecom-backup -microservice/config-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true